name: homekart
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  connectivity_plus: ^6.1.4
  cached_network_image: ^3.4.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  country_code_picker: ^3.3.0
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.12.3
  provider: ^6.1.5
  firebase_auth: ^6.0.0
  image_picker: ^1.1.2
  firebase_storage: ^13.0.0
  flutter_image_compress: ^2.4.0
  animated_text_kit: ^4.2.3
  firebase_app_check: ^0.4.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/app_assets/app_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path_android: "assets/app_assets/app_logo.png"
